name: Test-GitHub-Action

on:
  push:
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    name: Test GitHub Action
    steps:
      - name: Pull image
        run: |
          docker pull tutum/hello-world:latest

      - name: Scan
        strategy:
          matrix:
            IMAGE: [hello-world]
            IMAGE_TAG: [latest]
        uses: COPRS/reference-system-software@trivy-security-scan-v1
        with:
          IMAGE: ${{ matrix.IMAGE }}
          IMAGE_TAG: ${{ matrix.IMAGE_TAG }}
          EXIT_CODE: '1'
          SEVERITY: 'CRITICAL,HIGH'
          PROJECT: 'tutum'