name: Test-GitHub-Action

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test GitHub Action
    steps:
      - id: foo
        uses: sandbox-coprs/test-security-scan@master
        with:
          output-format: 'json,table,sarif'
