name: Test-GitHub-Action

on:
  push:
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    name: Test GitHub Action
    steps:
      - name: Pull image
        run: |
          docker pull tutum/hello-world:latest

      - name: Scan
        
        uses: COPRS/reference-system-software@trivy-security-scan-v1
        with:
          IMAGE_REF: 'tutum/hello-world:latest'
          EXIT_CODE: '1'
          SEVERITY: 'CRITICAL,HIGH'