name: Test-GitHub-Action

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test GitHub Action
    steps:
      - id: foo
        uses: actions/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
